export const workforcePermissionCodes = [
  "business:organizations:read",
  "business:organizations:update",
  "business:organizations:manage",
  "business:establishments:read",
  "business:establishments:update",
  "business:establishments:manage",
  "catalog:manage",
  "catalog:categories:create",
  "catalog:categories:read",
  "catalog:categories:update",
  "catalog:categories:delete",
  "catalog:categories:manage",
  "catalog:services:create",
  "catalog:services:read",
  "catalog:services:update",
  "catalog:services:delete",
  "catalog:services:manage",
  "crm:customers:create",
  "crm:customers:read",
  "crm:customers:update",
  "crm:customers:delete",
  "crm:customers:manage",
  "workforce:roles:create",
  "workforce:roles:read",
  "workforce:roles:update",
  "workforce:roles:delete",
  "workforce:roles:manage",
  "workforce:invitations:create",
  "workforce:invitations:read",
  "workforce:invitations:delete",
  "workforce:invitations:manage",
  "workforce:members:read",
  "workforce:members:delete",
  "workforce:members:manage",
  "scheduling:appointments:read",
  "scheduling:appointments:create",
  "scheduling:appointments:update",
  "scheduling:appointments:delete",
  "scheduling:appointments:manage",
] as const;

export type WorkforcePermission = (typeof workforcePermissionCodes)[number];

export function isWorkforcePermission(value: string): value is WorkforcePermission {
  return workforcePermissionCodes.includes(value as WorkforcePermission);
}
